# Generated by Django 2.2 on 2026-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('A', 'A栋'), ('B', 'B栋'), ('C', 'C栋'), ('D', 'D栋')], max_length=10, verbose_name='楼栋')),
                ('room_number', models.CharField(max_length=10, verbose_name='房间号')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('capacity', models.IntegerField(default=4, verbose_name='总容量')),
                ('current_count', models.IntegerField(default=0, verbose_name='当前人数')),
                ('room_type', models.CharField(choices=[('4人间', '4人间'), ('6人间', '6人间'), ('8人间', '8人间')], default='4人间', max_length=10, verbose_name='房型')),
                ('description', models.TextField(blank=True, default='', verbose_name='宿舍描述')),
            ],
            options={
                'verbose_name': '宿舍',
                'verbose_name_plural': '宿舍',
                'ordering': ['building', 'room_number'],
            },
        ),
    ]
